version: '3.8'

services:

  web:
    build: .
    command: poetry run python factory_bot/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/factory_bot
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  tgbot:
    build: .
    command: poetry run python factory_bot/manage.py bot
    env_file:
      - .env
    depends_on:
      - web

  db:
    image: postgres:15.3
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
